### ISSUE TITLE
Popover – align to the "edge" of a Trigger

### ISSUE THREAD

**Issue by mikrotron** [acl-services/paprika#182]
**Problem**
The only Popover alignments available are: top, bottom, right, left. The Popover content will always try to be aligned along the center of the trigger and content. For the `<DropdownMenu>` and `<DatePicker>` it is preferable to align the content to the left edge (if space permits) of the `<Trigger>` element.  

![image](https://user-images.githubusercontent.com/4040102/61498124-e2ee1680-a976-11e9-8c27-39275c1943d1.png)
![image](https://user-images.githubusercontent.com/4040102/61498136-eda8ab80-a976-11e9-8581-425053961d0d.png)

**Suggested solution**
Add a new `edge` alignment option that will open the Popover below the trigger, with left edges aligned.  If space is insufficient, the Popover will adapt automatically to align to the right edge / above the Trigger.

**Comment by nahumzs** [comment]
would the default edge alignment be left/right? or how the popover would align if it's a the center of the screen without constrains?

**Comment by mikrotron** [comment]
So, that's an open question for a designer, but my proposal is the default is "open the Popover below the trigger, with left edges aligned".  It would only adjust to use the right edge, or open above the trigger if it doesn't fit.

**Comment by jayde-acl** [comment]
@nahumzs Sounds like the default `edge` alignment will be left if there are no constraints. 

@mikrotron The proposed solution sounds like it would work well, I do have a question though. There appear to be cases in our designs where most of the dropdown menus are right-aligned to the trigger.

Does the dropdown menu popover also use this component? Is it worthwhile to add in an `edge-right` as well as the `edge-left` instead of just `edge`?

Examples:
- Projects / Assurance Plans - ellipsis to trigger - dropdown menu with edit & delete options
https://acl.invisionapp.com/share/3XO2W7HND7E#/320207010_Delete_Assurance_Plan

- Projects / Project - Certifications - ellipsis to trigger dropdown menu with various options
https://acl.invisionapp.com/share/GXQEQPFNHM8#/351796991_Deleting_Certification_-_1

- Projects / Scheduler / Add new trigger dropdown menu 

I am sure that there are many more of these `edge-right` popover menus throughout our platform, these are just the ones I've seen recently.

I'm also trying to think of the last time I've seen someone use `top` while designing. Is this one necessary? I'm assuming that `top` means for the popover to appear above the trigger.

cc @johnpeele

**Comment by nahumzs** [comment]
`top` shouldn't be necessary because if there is not space or the button is at the bottom of the page will automatically show at the top. Seems to me as well like left and right might need to be required.

**Comment by jayde-acl** [comment]
Chatted with @johnpeele and he confirms that having the 2 props, edge-right and edge-left, is needed. I think @mikrotron is right that edge-right as the default makes sense after thinking about it.
