### ISSUE TITLE
Modal content focus outline hidden at the bottom by footer

### ISSUE THREAD

**Issue by alexzherdev** [acl-services/paprika#365]
# Bug Report
## Expected behavior
The focus outline is fully visible when modal's content is focused.

## Current behavior
When the modal is short (i.e. there is no vertical scrolling), the bottom part of the outline is hidden by the footer.

## Screenshots / Gifs / Codepens
![image](https://user-images.githubusercontent.com/93752/71596847-c3e2db80-2af5-11ea-840d-44482c92837b.png)

## Additional context
Looks like I can fix this by setting `z-index: 0` on the content element, but not sure that's the right way to go.

**Comment by mikrotron** [comment]
@alexzherdev yeah this is not ideal, but we are planning to change it soon. We will use a custom styled focus indicator, but since this is not an input or control, we're probably going to use a more subtle design than the usual one which we have a token for.  @sunminsarahlee is working on it, and we'll update the component when she's got approval from the design team.

**Comment by mikrotron** [comment]
Style will be `2px dotted #8a8a8a`.
